debug: false

logging:
  config: file:logback.xml

server:
  port: 7033

service:
  endpoint: service
  secret: secret

queue:
  config:
    host: localhost
    port: 5672
    heartbeat: 10
    username: username
    password: password
    retry.interval: 10
    rpc:
      queue: WS-IN
      timeout: 30000

spring:
  mandatoryFileEncoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
    password: root
    sqlScriptEncoding: UTF-8
    tomcat.connection-properties: useUnicode=yes;characterEncoding=utf-8;
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 8
      maximum-pool-size: 24
      pool-name: oracle-pool
      auto-commit: true
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        #globally_quoted_identifiers: true
        id.new_generator_mappings: false
